//! A log written before the `hlc` feature existed must keep verifying once it
//! is enabled. The `hlc` field is skipped when absent, so these entries
//! canonicalize to exactly the bytes that were originally signed.
//!
//! The fixture below is real output from a build with `hlc` off, captured
//! verbatim. Regenerating it defeats the purpose: it is here to catch a future
//! change to the canonical form that would silently invalidate deployed logs.

#![cfg(feature = "hmac-chain")]

use ash_log::{AuditEvent, HmacChainIntegrity};

const KEY: &[u8] = b"test-key-at-least-32-bytes-long!!";

/// Five chained events, serialized by a build without the `hlc` feature.
const PRE_HLC_CHAIN: &[&str] = &[
    r#"{"timestamp":1788768421420340155,"event_type":"authentication_attempt","correlation_id":null,"remote_addr":null,"principal":"user0","method":null,"result":"success","severity":"info","metadata":{"mac":"8cd28273b1c371c9d568bd4793a11d6d323b25c61c14a1a2223302b30392a5c9","chain_index":0},"params":null,"error":null}"#,
    r#"{"timestamp":1788768421420481779,"event_type":"authentication_attempt","correlation_id":null,"remote_addr":null,"principal":"user1","method":null,"result":"success","severity":"info","metadata":{"chain_index":1,"mac":"b08babf139024bcf30b1fe2f55b3e4820f1ae9f75bcebd6b4f1ecb62ea6cd0e8"},"params":null,"error":null}"#,
    r#"{"timestamp":1788768421420598377,"event_type":"authentication_attempt","correlation_id":null,"remote_addr":null,"principal":"user2","method":null,"result":"success","severity":"info","metadata":{"mac":"7d1b33b1575a556c426ff7fef6d7d2afc5e1f2bb7c61e217f892afdad951d916","chain_index":2},"params":null,"error":null}"#,
    r#"{"timestamp":1788768421420752850,"event_type":"authentication_attempt","correlation_id":null,"remote_addr":null,"principal":"user3","method":null,"result":"success","severity":"info","metadata":{"mac":"36b0e003b9e121ff2121708f420bfe12cebe18ec7313e49814147948171111a6","chain_index":3},"params":null,"error":null}"#,
    r#"{"timestamp":1788768421420950320,"event_type":"authentication_attempt","correlation_id":null,"remote_addr":null,"principal":"user4","method":null,"result":"success","severity":"info","metadata":{"mac":"064f22282c3b05745af2db8d1974669d835690f746ea67020b63dd0a3f9f99f1","chain_index":4},"params":null,"error":null}"#,
];

#[test]
fn test_a_pre_hlc_log_still_verifies() {
    let events: Vec<AuditEvent> = PRE_HLC_CHAIN
        .iter()
        .map(|line| serde_json::from_str(line).expect("fixture parses"))
        .collect();

    assert_eq!(
        HmacChainIntegrity::new(KEY).verify_chain(&events),
        Ok(5),
        "the canonical form of an event without a causal timestamp is unchanged"
    );
}

#[test]
fn test_the_fixture_carries_no_hlc_field() {
    // If this fails, the fixture was regenerated by an hlc-enabled build and no
    // longer tests what it claims to.
    for line in PRE_HLC_CHAIN {
        assert!(
            !line.contains("hlc"),
            "fixture must predate the field it guards against"
        );
    }
}

/// Tampering is still detected in a pre-feature log.
#[test]
fn test_a_pre_hlc_log_still_detects_edits() {
    let mut events: Vec<AuditEvent> = PRE_HLC_CHAIN
        .iter()
        .map(|line| serde_json::from_str(line).expect("fixture parses"))
        .collect();

    events[3].principal = Some("attacker".to_string());

    assert!(
        HmacChainIntegrity::new(KEY).verify_chain(&events).is_err(),
        "an edited entry fails verification regardless of the hlc feature"
    );
}
